// src/lib/components/layout/Sidebar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { settings, sidebarOpen, reader } from '$lib/stores';
	import { isSectionRead, calcChapterProgress, scrollProgress } from '$lib/stores/reader';
	import { onMount } from 'svelte';
	import type { TableOfContents, Chapter } from '$lib/types/content';
	import { loadTableOfContents, getChapterPath, getSectionPath, findChapterBySlug } from '$lib/utils/contentLoader';

	export let bookSlug: string = '';
	export let hasPeriodicTable: boolean = false;

	let toc: TableOfContents | null = null;
	let manuallyToggledChapters: Set<number> = new Set();

	// Get current route params
	$: chapterParam = $page.params.chapterSlug;
	$: sectionParam = $page.params.sectionSlug;

	// Subscribe to reader progress for reactivity
	$: progress = $reader.progress;

	// Load table of contents
	onMount(async () => {
		if (bookSlug) {
			try {
				toc = await loadTableOfContents(bookSlug);
			} catch (error) {
				console.error('Gat ekki hlaðið efnisyfirliti:', error);
			}
		}
	});

	// Calculate which chapters should be expanded
	$: expandedChapters = (() => {
		const expanded = new Set<number>();
		if (!toc) return expanded;

		const currentChapter = chapterParam ? findChapterBySlug(toc, chapterParam) : null;
		const currentChapterNumber = currentChapter?.number;
		const autoExpandChapter = currentChapterNumber ?? 1;

		if (!manuallyToggledChapters.has(autoExpandChapter)) {
			expanded.add(autoExpandChapter);
		}

		manuallyToggledChapters.forEach((chapterNumber) => {
			if (chapterNumber !== autoExpandChapter) {
				expanded.add(chapterNumber);
			}
		});

		return expanded;
	})();

	function toggleChapter(chapterNumber: number) {
		const newSet = new Set(manuallyToggledChapters);
		if (newSet.has(chapterNumber)) {
			newSet.delete(chapterNumber);
		} else {
			newSet.add(chapterNumber);
		}
		manuallyToggledChapters = newSet;
	}

	function closeSidebar() {
		settings.setSidebarOpen(false);
	}

	// Reactive helpers using subscribed progress (use chapter/section paths)
	function isRead(chapterPath: string, sectionPath: string): boolean {
		return isSectionRead(progress, chapterPath, sectionPath);
	}

	function getChapterProgressPercent(chapter: Chapter): number {
		return calcChapterProgress(progress, getChapterPath(chapter), chapter.sections.length);
	}
</script>

<!-- Overlay (backdrop) -->
<div
	class="fixed inset-0 z-40 bg-black/20 backdrop-blur-sm transition-opacity duration-300 lg:hidden {$sidebarOpen
		? 'opacity-100'
		: 'pointer-events-none opacity-0'}"
	on:click={closeSidebar}
	on:keydown={(e) => e.key === 'Escape' && closeSidebar()}
	role="button"
	tabindex="-1"
	aria-hidden="true"
></div>

<!-- Sidebar -->
<aside
	aria-hidden={!$sidebarOpen ? 'true' : undefined}
	class="
    fixed
    inset-y-0 lg:top-[7rem] left-0
    z-50 lg:z-30
    w-80 bg-white dark:bg-gray-900
    transition-transform duration-300 ease-out
    overflow-y-auto
    lg:h-[calc(100vh-7rem)]
    {$sidebarOpen ? 'translate-x-0 shadow-2xl' : '-translate-x-full lg:translate-x-0'}
    lg:shadow-none
    lg:border-r lg:border-gray-200 dark:lg:border-gray-700
  "
>
	<div class="flex h-full flex-col">
		<!-- Sidebar header -->
		<div class="flex h-14 items-center justify-between border-b border-gray-100 dark:border-gray-800 px-4">
			<h2 class="font-semibold text-gray-900 dark:text-gray-100">Efnisyfirlit</h2>
			<button
				on:click={closeSidebar}
				class="rounded-lg p-2 -mr-2 text-gray-500 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 hover:text-gray-700 dark:hover:text-gray-200 lg:hidden"
				aria-label="Loka valmynd"
			>
				<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
				</svg>
			</button>
		</div>

		<!-- Sidebar content -->
		<nav class="flex-1 overflow-y-auto py-4" aria-label="Efnisyfirlit">
			{#if !toc}
				<p class="text-gray-500 dark:text-gray-300 px-4">Hleður efnisyfirlit...</p>
			{:else}
				<ul class="space-y-1 px-2">
					{#each toc.chapters as chapter (chapter.number)}
						{@const chapterPath = getChapterPath(chapter)}
						{@const progressPercent = getChapterProgressPercent(chapter)}
						{@const expanded = expandedChapters.has(chapter.number)}
						{@const isCurrentChapter = chapterParam === chapterPath || chapterParam === chapter.slug}
						<li>
							<!-- Chapter progress indicator -->
							{#if progressPercent > 0}
								<div class="mb-2 px-4">
									<div class="mb-2 flex items-center justify-between">
										<span class="text-xs font-medium uppercase tracking-wider text-gray-500 dark:text-gray-300">
											{chapter.number}. kafli
										</span>
										<span class="text-xs font-medium text-emerald-600 dark:text-emerald-400">
											{progressPercent}%
										</span>
									</div>
									<div class="h-1 overflow-hidden rounded-full bg-gray-100 dark:bg-gray-700">
										<div class="h-full rounded-full bg-emerald-500" style="width: {progressPercent}%"></div>
									</div>
								</div>
							{/if}

							<button
								on:click={() => toggleChapter(chapter.number)}
								aria-expanded={expanded}
								aria-controls="chapter-{chapter.number}-sections"
								class="flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left font-medium text-gray-700 dark:text-gray-200 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800"
							>
								<span class="flex items-center gap-2">
									{#if expanded}
										<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
										</svg>
									{:else}
										<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
										</svg>
									{/if}
									<span>{chapter.number}. {chapter.title}</span>
								</span>
							</button>

							<!-- Sections -->
							{#if expanded}
								<ul id="chapter-{chapter.number}-sections" class="mt-1 space-y-1">
									{#each chapter.sections as section (section.number)}
										{@const sectionPath = getSectionPath(section)}
										{@const isCurrent = isCurrentChapter && (sectionParam === sectionPath || sectionParam === section.slug)}
										{@const isReadSection = isRead(chapterPath, sectionPath)}
										<li>
											<a
												href="/{bookSlug}/kafli/{chapterPath}/{sectionPath}"
												class="flex items-center gap-3 rounded-lg px-3 py-2.5 transition-colors {isCurrent
													? 'bg-blue-50 dark:bg-blue-900/30 font-medium text-blue-700 dark:text-blue-300'
													: 'text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800'}"
											>
												{#if isReadSection}
													<span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-emerald-100 dark:bg-emerald-900/50">
														<svg class="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
															<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
														</svg>
													</span>
												{:else if isCurrent}
													<!-- Scroll progress ring for current section -->
													<span class="relative flex h-6 w-6 shrink-0 items-center justify-center">
														<svg class="absolute w-6 h-6 -rotate-90" viewBox="0 0 24 24">
															<circle
																cx="12" cy="12" r="10"
																fill="none"
																stroke="currentColor"
																stroke-width="2"
																class="text-blue-100 dark:text-blue-900/50"
															/>
															<circle
																cx="12" cy="12" r="10"
																fill="none"
																stroke="currentColor"
																stroke-width="2"
																stroke-dasharray="62.83"
																stroke-dashoffset={62.83 - (62.83 * $scrollProgress / 100)}
																stroke-linecap="round"
																class="text-blue-500 dark:text-blue-400 transition-[stroke-dashoffset] duration-150"
															/>
														</svg>
														<span class="h-2 w-2 rounded-full bg-blue-600 dark:bg-blue-400"></span>
													</span>
												{:else}
													<span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gray-100 dark:bg-gray-700">
														<span class="h-2 w-2 rounded-full bg-gray-300 dark:bg-gray-500"></span>
													</span>
												{/if}
												<span class="text-sm">{section.number} {section.title}</span>
											</a>
										</li>
									{/each}
								</ul>
							{/if}
						</li>
					{/each}
				</ul>

				<!-- Study tools section -->
				<div class="mt-6 space-y-1 border-t border-gray-100 dark:border-gray-800 px-2 pt-4">
					<h3 class="px-3 py-2 text-xs font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-300">
						Námsverkfæri
					</h3>
					<a
						href="/{bookSlug}/ordabok"
						class="flex items-center gap-3 rounded-lg px-3 py-2.5 text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800 hover:text-gray-900 dark:hover:text-white"
					>
						<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
						</svg>
						<span class="text-sm">Orðasafn</span>
					</a>
					<a
						href="/{bookSlug}/minniskort"
						class="flex items-center gap-3 rounded-lg px-3 py-2.5 text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800 hover:text-gray-900 dark:hover:text-white"
					>
						<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
						</svg>
						<span class="text-sm">Minniskort</span>
					</a>
					<a
						href="/{bookSlug}/aefingar"
						class="flex items-center gap-3 rounded-lg px-3 py-2.5 text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800 hover:text-gray-900 dark:hover:text-white"
					>
						<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
						</svg>
						<span class="text-sm">Æfingadæmi</span>
					</a>
					<a
						href="/{bookSlug}/markmid"
						class="flex items-center gap-3 rounded-lg px-3 py-2.5 text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800 hover:text-gray-900 dark:hover:text-white"
					>
						<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
						</svg>
						<span class="text-sm">Námsmarkmið</span>
					</a>
					<a
						href="/{bookSlug}/greining"
						class="flex items-center gap-3 rounded-lg px-3 py-2.5 text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800 hover:text-gray-900 dark:hover:text-white"
					>
						<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
						</svg>
						<span class="text-sm">Námsgreining</span>
					</a>
					<a
						href="/{bookSlug}/bokamerki"
						class="flex items-center gap-3 rounded-lg px-3 py-2.5 text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800 hover:text-gray-900 dark:hover:text-white"
					>
						<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
						</svg>
						<span class="text-sm">Bókamerki</span>
					</a>
					{#if hasPeriodicTable}
						<a
							href="/{bookSlug}/lotukerfi"
							class="flex items-center gap-3 rounded-lg px-3 py-2.5 text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800 hover:text-gray-900 dark:hover:text-white"
						>
							<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
								<circle cx="12" cy="12" r="3" stroke-width="2" />
								<ellipse cx="12" cy="12" rx="9" ry="4" stroke-width="2" />
								<ellipse cx="12" cy="12" rx="9" ry="4" transform="rotate(60 12 12)" stroke-width="2" />
								<ellipse cx="12" cy="12" rx="9" ry="4" transform="rotate(120 12 12)" stroke-width="2" />
							</svg>
							<span class="text-sm">Lotukerfi</span>
						</a>
					{/if}
				</div>
			{/if}
		</nav>
	</div>
</aside>

// src/components/layout/Sidebar.tsx
import { useState, useEffect } from "react";
import { Link, useParams } from "react-router-dom";
import {
  ChevronDown,
  ChevronRight,
  Check,
  X,
  BookOpen,
  Brain,
  Target,
  BarChart3,
  CheckSquare,
  Bookmark,
  Atom,
} from "lucide-react";
import { useSettingsStore } from "@/stores/settingsStore";
import { useReaderStore } from "@/stores/readerStore";
import { useBook } from "@/hooks/useBook";
import { loadTableOfContents } from "@/utils/contentLoader";
import type { TableOfContents, Chapter } from "@/types/content";

export default function Sidebar() {
  const { sidebarOpen, setSidebarOpen } = useSettingsStore();
  const { isRead, getChapterProgress } = useReaderStore();
  const { bookSlug, book } = useBook();
  const [toc, setToc] = useState<TableOfContents | null>(null);
  // Track which chapters user has manually toggled
  const [manuallyToggledChapters, setManuallyToggledChapters] = useState<
    Set<number>
  >(new Set());
  const { chapterSlug, sectionSlug } = useParams();

  // Load table of contents on mount
  useEffect(() => {
    if (!bookSlug) return;
    loadTableOfContents(bookSlug)
      .then(setToc)
      .catch((error) => {
        console.error("Gat ekki hlaðið efnisyfirliti:", error);
      });
  }, [bookSlug]);

  // Calculate which chapters should be expanded
  // Logic: Only the current chapter auto-expands. Other chapters stay collapsed
  // unless manually expanded by the user.
  const expandedChapters = new Set<number>();

  if (toc) {
    // Find current chapter number
    const currentChapter = chapterSlug
      ? toc.chapters.find((c) => c.slug === chapterSlug)
      : null;
    const currentChapterNumber = currentChapter?.number;

    // Auto-expand current chapter (or chapter 1 if no chapter is being viewed)
    const autoExpandChapter = currentChapterNumber ?? 1;

    // Only auto-expand if user hasn't manually collapsed it
    if (!manuallyToggledChapters.has(autoExpandChapter)) {
      expandedChapters.add(autoExpandChapter);
    }

    // Add any chapters the user has manually expanded
    manuallyToggledChapters.forEach((chapterNumber) => {
      // If it's the auto-expand chapter and was toggled, it means user collapsed it
      // If it's a different chapter and was toggled, it means user expanded it
      if (chapterNumber !== autoExpandChapter) {
        expandedChapters.add(chapterNumber);
      }
    });
  }

  const toggleChapter = (chapterNumber: number) => {
    setManuallyToggledChapters((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(chapterNumber)) {
        newSet.delete(chapterNumber);
      } else {
        newSet.add(chapterNumber);
      }
      return newSet;
    });
  };

  if (!toc) {
    return (
      <aside className="fixed left-0 top-14 lg:top-[7rem] z-30 h-[calc(100vh-3.5rem)] lg:h-[calc(100vh-7rem)] w-80 overflow-y-auto bg-white dark:bg-gray-900 p-4 shadow-none">
        <p className="text-gray-500 dark:text-gray-400">Hleður efnisyfirlit...</p>
      </aside>
    );
  }

  return (
    <>
      {/* Overlay (backdrop) */}
      <div
        className={`fixed inset-0 z-40 bg-black/20 backdrop-blur-sm transition-opacity duration-300 lg:hidden ${
          sidebarOpen ? "opacity-100" : "pointer-events-none opacity-0"
        }`}
        onClick={() => setSidebarOpen(false)}
        aria-hidden="true"
      />

      {/* Sidebar */}
      <aside
        aria-hidden={!sidebarOpen ? "true" : undefined}
        className={`
          fixed
          inset-y-0 lg:top-[7rem] left-0
          z-50 lg:z-30
          w-80 bg-white dark:bg-gray-900
          transition-transform duration-300 ease-out
          overflow-y-auto
          lg:h-[calc(100vh-7rem)]
          ${sidebarOpen ? "translate-x-0 shadow-2xl" : "-translate-x-full lg:translate-x-0"}
          lg:shadow-none
        `}
      >
        <div className="flex h-full flex-col">
          {/* Sidebar header */}
          <div className="flex h-14 items-center justify-between border-b border-gray-100 dark:border-gray-800 px-4">
            <h2 className="font-semibold text-gray-900 dark:text-gray-100">Efnisyfirlit</h2>
            <button
              onClick={() => setSidebarOpen(false)}
              className="rounded-lg p-2 -mr-2 text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 hover:text-gray-700 dark:hover:text-gray-200 lg:hidden"
              aria-label="Loka valmynd"
            >
              <X size={20} />
            </button>
          </div>

          {/* Sidebar content */}
          <nav
            className="flex-1 overflow-y-auto py-4"
            aria-label="Efnisyfirlit"
          >
            <ul className="space-y-1 px-2">
              {toc.chapters.map((chapter) => (
                <ChapterItem
                  key={chapter.number}
                  chapter={chapter}
                  bookSlug={bookSlug}
                  expanded={expandedChapters.has(chapter.number)}
                  onToggle={() => toggleChapter(chapter.number)}
                  currentChapter={chapterSlug}
                  currentSection={sectionSlug}
                  isRead={isRead}
                  progress={getChapterProgress(
                    chapter.slug,
                    chapter.sections.length,
                  )}
                />
              ))}
            </ul>

            {/* Study tools section */}
            <div className="mt-6 space-y-1 border-t border-gray-100 dark:border-gray-800 px-2 pt-4">
              <h3 className="px-3 py-2 text-xs font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400">
                Námsverkfæri
              </h3>
              <Link
                to={`/${bookSlug}/ordabok`}
                className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800 hover:text-gray-900 dark:hover:text-white"
              >
                <BookOpen size={20} />
                <span className="text-sm">Orðasafn</span>
              </Link>
              <Link
                to={`/${bookSlug}/minniskort`}
                className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800 hover:text-gray-900 dark:hover:text-white"
              >
                <Brain size={20} />
                <span className="text-sm">Minniskort</span>
              </Link>
              <Link
                to={`/${bookSlug}/aefingar`}
                className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800 hover:text-gray-900 dark:hover:text-white"
              >
                <Target size={20} />
                <span className="text-sm">Æfingadæmi</span>
              </Link>
              <Link
                to={`/${bookSlug}/markmid`}
                className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800 hover:text-gray-900 dark:hover:text-white"
              >
                <CheckSquare size={20} />
                <span className="text-sm">Námsmarkmið</span>
              </Link>
              <Link
                to={`/${bookSlug}/greining`}
                className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800 hover:text-gray-900 dark:hover:text-white"
              >
                <BarChart3 size={20} />
                <span className="text-sm">Námsgreining</span>
              </Link>
              <Link
                to={`/${bookSlug}/bokamerki`}
                className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800 hover:text-gray-900 dark:hover:text-white"
              >
                <Bookmark size={20} />
                <span className="text-sm">Bókamerki</span>
              </Link>
              {book?.features?.periodicTable && (
                <Link
                  to={`/${bookSlug}/lotukerfi`}
                  className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800 hover:text-gray-900 dark:hover:text-white"
                >
                  <Atom size={20} />
                  <span className="text-sm">Lotukerfi</span>
                </Link>
              )}
            </div>
          </nav>
        </div>
      </aside>
    </>
  );
}

// Chapter item component
interface ChapterItemProps {
  chapter: Chapter;
  bookSlug: string;
  expanded: boolean;
  onToggle: () => void;
  currentChapter?: string;
  currentSection?: string;
  isRead: (chapterSlug: string, sectionSlug: string) => boolean;
  progress: number;
}

function ChapterItem({
  chapter,
  bookSlug,
  expanded,
  onToggle,
  currentChapter,
  currentSection,
  isRead,
  progress,
}: ChapterItemProps) {
  const isCurrentChapter = currentChapter === chapter.slug;

  return (
    <li>
      {/* Chapter progress indicator */}
      {progress > 0 && (
        <div className="mb-2 px-4">
          <div className="mb-2 flex items-center justify-between">
            <span className="text-xs font-medium uppercase tracking-wider text-gray-500 dark:text-gray-400">
              {chapter.number}. kafli
            </span>
            <span className="text-xs font-medium text-emerald-600 dark:text-emerald-400">
              {progress}%
            </span>
          </div>
          <div className="h-1 overflow-hidden rounded-full bg-gray-100 dark:bg-gray-700">
            <div
              className="h-full rounded-full bg-emerald-500"
              style={{ width: `${progress}%` }}
            />
          </div>
        </div>
      )}

      <button
        onClick={onToggle}
        aria-expanded={expanded}
        aria-controls={`chapter-${chapter.number}-sections`}
        className="flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left font-medium text-gray-700 dark:text-gray-200 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800"
      >
        <span className="flex items-center gap-2">
          {expanded ? <ChevronDown size={18} /> : <ChevronRight size={18} />}
          <span>
            {chapter.number}. {chapter.title}
          </span>
        </span>
      </button>

      {/* Sections */}
      {expanded && (
        <ul
          id={`chapter-${chapter.number}-sections`}
          className="mt-1 space-y-1"
        >
          {chapter.sections.map((section) => {
            const isCurrent =
              isCurrentChapter && currentSection === section.slug;
            const isReadSection = isRead(chapter.slug, section.slug);

            return (
              <li key={section.slug}>
                <Link
                  to={`/${bookSlug}/kafli/${chapter.slug}/${section.slug}`}
                  className={`flex items-center gap-3 rounded-lg px-3 py-2.5 transition-colors ${
                    isCurrent
                      ? "bg-blue-50 dark:bg-blue-900/30 font-medium text-blue-700 dark:text-blue-300"
                      : "text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800"
                  }`}
                >
                  {isReadSection ? (
                    <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-emerald-100 dark:bg-emerald-900/50">
                      <Check size={14} className="text-emerald-600 dark:text-emerald-400" />
                    </span>
                  ) : isCurrent ? (
                    <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-900/50">
                      <span className="h-2 w-2 rounded-full bg-blue-600 dark:bg-blue-400" />
                    </span>
                  ) : (
                    <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gray-100 dark:bg-gray-700">
                      <span className="h-2 w-2 rounded-full bg-gray-300 dark:bg-gray-500" />
                    </span>
                  )}
                  <span className="text-sm">
                    {section.number} {section.title}
                  </span>
                </Link>
              </li>
            );
          })}
        </ul>
      )}
    </li>
  );
}
