// src/components/reader/FlashcardModal.tsx
import { useState, useRef, useEffect } from "react";
import { X, Save, Plus, BookOpen } from "lucide-react";
import { useFlashcardStore } from "@/stores/flashcardStore";
import type { Flashcard, FlashcardDeck } from "@/types/flashcard";

// =============================================================================
// TYPES
// =============================================================================

interface FlashcardModalProps {
  selectedText: string;
  bookSlug: string;
  chapterSlug?: string;
  sectionSlug?: string;
  onSave: () => void;
  onClose: () => void;
}

// =============================================================================
// COMPONENT
// =============================================================================

export default function FlashcardModal({
  selectedText,
  bookSlug,
  chapterSlug,
  sectionSlug,
  onSave,
  onClose,
}: FlashcardModalProps) {
  const { decks, addDeck, addCardToDeck } = useFlashcardStore();
  const [back, setBack] = useState("");
  // Initialize with first deck or empty if no decks
  const [selectedDeckId, setSelectedDeckId] = useState<string>(() =>
    decks.length > 0 ? decks[0].id : "",
  );
  // Show new deck form if no existing decks
  const [showNewDeck, setShowNewDeck] = useState(() => decks.length === 0);
  const [newDeckName, setNewDeckName] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Focus textarea on mount
  useEffect(() => {
    textareaRef.current?.focus();
  }, []);

  // Handle Escape key
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        onClose();
      }
    };

    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [onClose]);

  const handleSave = () => {
    if (!back.trim()) return;

    let deckId = selectedDeckId;

    // Create new deck if needed
    if (showNewDeck && newDeckName.trim()) {
      const newDeck: FlashcardDeck = {
        id: `deck-${Date.now()}`,
        name: newDeckName.trim(),
        description: `Minniskort frá ${bookSlug}`,
        cards: [],
        created: new Date().toISOString(),
      };
      addDeck(newDeck);
      deckId = newDeck.id;
    }

    if (!deckId) return;

    // Create the flashcard
    const card: Flashcard = {
      id: `card-${Date.now()}`,
      front: selectedText,
      back: back.trim(),
      category: chapterSlug || bookSlug,
      source: sectionSlug
        ? `${bookSlug}/${chapterSlug}/${sectionSlug}`
        : "highlight",
      created: new Date().toISOString(),
    };

    addCardToDeck(deckId, card);
    onSave();
  };

  const handleKeyDown = (event: React.KeyboardEvent) => {
    // Save with Ctrl/Cmd + Enter
    if (event.key === "Enter" && (event.ctrlKey || event.metaKey)) {
      event.preventDefault();
      handleSave();
    }
  };

  const canSave =
    back.trim() && (selectedDeckId || (showNewDeck && newDeckName.trim()));

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
      data-modal-overlay="true"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
      role="dialog"
      aria-modal="true"
      aria-labelledby="flashcard-modal-title"
    >
      <div className="mx-4 w-full max-w-lg rounded-xl border border-[var(--border-color)] bg-[var(--bg-secondary)] shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-[var(--border-color)] px-6 py-4">
          <h2
            id="flashcard-modal-title"
            className="font-sans text-lg font-semibold text-[var(--text-primary)]"
          >
            Búa til minniskort
          </h2>
          <button
            onClick={onClose}
            className="rounded-lg p-2 text-[var(--text-secondary)] transition-colors hover:bg-[var(--bg-primary)] hover:text-[var(--text-primary)]"
            aria-label="Loka"
          >
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6">
          {/* Front of card (selected text) */}
          <div className="mb-4">
            <label className="mb-2 flex items-center gap-2 font-sans text-sm font-medium text-[var(--text-secondary)]">
              <BookOpen size={14} />
              Fremri hlið (spurning/hugtak)
            </label>
            <blockquote className="rounded-lg border-l-4 border-[var(--accent-color)] bg-[var(--bg-primary)] p-3 text-sm text-[var(--text-primary)]">
              {selectedText.length > 300
                ? `${selectedText.slice(0, 300)}...`
                : selectedText}
            </blockquote>
          </div>

          {/* Back of card (user input) */}
          <div className="mb-4">
            <label
              htmlFor="flashcard-back"
              className="mb-2 block font-sans text-sm font-medium text-[var(--text-secondary)]"
            >
              Aftari hlið (svar/skilgreining) *
            </label>
            <textarea
              ref={textareaRef}
              id="flashcard-back"
              value={back}
              onChange={(e) => setBack(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Skrifaðu svarið eða skilgreininguna hér..."
              className="min-h-[100px] w-full resize-y rounded-lg border border-[var(--border-color)] bg-[var(--bg-primary)] p-3 text-[var(--text-primary)] placeholder-[var(--text-secondary)] focus:border-[var(--accent-color)] focus:outline-none focus:ring-2 focus:ring-[var(--accent-color)]/20"
              required
            />
            <p className="mt-1 font-sans text-xs text-[var(--text-secondary)]">
              Ýttu á Ctrl+Enter til að vista
            </p>
          </div>

          {/* Deck selection */}
          <div className="mb-4">
            <label className="mb-2 block font-sans text-sm font-medium text-[var(--text-secondary)]">
              Veldu stokkinn
            </label>

            {decks.length > 0 && !showNewDeck && (
              <div className="space-y-2">
                <select
                  value={selectedDeckId}
                  onChange={(e) => setSelectedDeckId(e.target.value)}
                  className="w-full rounded-lg border border-[var(--border-color)] bg-[var(--bg-primary)] p-3 text-[var(--text-primary)] focus:border-[var(--accent-color)] focus:outline-none focus:ring-2 focus:ring-[var(--accent-color)]/20"
                >
                  {decks.map((deck) => (
                    <option key={deck.id} value={deck.id}>
                      {deck.name} ({deck.cards.length} kort)
                    </option>
                  ))}
                </select>
                <button
                  type="button"
                  onClick={() => setShowNewDeck(true)}
                  className="flex items-center gap-1 text-sm text-[var(--accent-color)] hover:underline"
                >
                  <Plus size={14} />
                  Búa til nýjan stokk
                </button>
              </div>
            )}

            {(showNewDeck || decks.length === 0) && (
              <div className="space-y-2">
                <input
                  type="text"
                  value={newDeckName}
                  onChange={(e) => setNewDeckName(e.target.value)}
                  placeholder="Nafn á nýjum stokk..."
                  className="w-full rounded-lg border border-[var(--border-color)] bg-[var(--bg-primary)] p-3 text-[var(--text-primary)] placeholder-[var(--text-secondary)] focus:border-[var(--accent-color)] focus:outline-none focus:ring-2 focus:ring-[var(--accent-color)]/20"
                />
                {decks.length > 0 && (
                  <button
                    type="button"
                    onClick={() => {
                      setShowNewDeck(false);
                      setNewDeckName("");
                    }}
                    className="text-sm text-[var(--text-secondary)] hover:underline"
                  >
                    Hætta við og velja núverandi stokk
                  </button>
                )}
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="flex justify-end gap-3 border-t border-[var(--border-color)] px-6 py-4">
          <button
            onClick={onClose}
            className="rounded-lg border border-[var(--border-color)] px-4 py-2 font-sans text-sm font-medium text-[var(--text-secondary)] transition-colors hover:bg-[var(--bg-primary)]"
          >
            Hætta við
          </button>
          <button
            onClick={handleSave}
            disabled={!canSave}
            className="flex items-center gap-2 rounded-lg bg-[var(--accent-color)] px-4 py-2 font-sans text-sm font-medium text-white transition-colors hover:bg-[var(--accent-hover)] disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Save size={16} />
            Vista minniskort
          </button>
        </div>
      </div>
    </div>
  );
}

// src/lib/components/FlashcardModal.svelte
<!--
  FlashcardModal - Modal for creating flashcards from highlighted text
-->
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { fade, scale } from 'svelte/transition';
	import { flashcardStore } from '$lib/stores/flashcard';
	import type { Flashcard, FlashcardDeck } from '$lib/types/flashcard';

	export let selectedText: string;
	export let source: string = ''; // e.g., "Efnafræði 2e > 1.1 Efnafræði í samhengi"
	export let onSave: () => void;
	export let onClose: () => void;

	let back = '';
	let selectedDeckId = '';
	let newDeckName = '';
	let showNewDeckInput = false;
	let backTextarea: HTMLTextAreaElement;

	// Get decks from store
	$: decks = $flashcardStore.decks;

	// Auto-select first deck if available
	$: if (decks.length > 0 && !selectedDeckId && !showNewDeckInput) {
		selectedDeckId = decks[0].id;
	}

	function generateId(): string {
		return `${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
	}

	function handleSave() {
		if (!back.trim()) return;

		let deckId = selectedDeckId;

		// Create new deck if needed
		if (showNewDeckInput && newDeckName.trim()) {
			const newDeck: FlashcardDeck = {
				id: generateId(),
				name: newDeckName.trim(),
				cards: [],
				created: new Date().toISOString()
			};
			flashcardStore.addDeck(newDeck);
			deckId = newDeck.id;
		}

		if (!deckId) return;

		// Create the flashcard
		const card: Flashcard = {
			id: generateId(),
			front: selectedText,
			back: back.trim(),
			source: source || undefined,
			created: new Date().toISOString()
		};

		flashcardStore.addCardToDeck(deckId, card);
		onSave();
	}

	function handleKeyDown(event: KeyboardEvent) {
		// Save with Ctrl/Cmd + Enter
		if (event.key === 'Enter' && (event.ctrlKey || event.metaKey)) {
			event.preventDefault();
			handleSave();
		}
		// Close on Escape
		if (event.key === 'Escape') {
			onClose();
		}
	}

	function handleOverlayClick(event: MouseEvent) {
		if (event.target === event.currentTarget) {
			onClose();
		}
	}

	function toggleNewDeck() {
		showNewDeckInput = !showNewDeckInput;
		if (!showNewDeckInput) {
			newDeckName = '';
		}
	}

	onMount(() => {
		backTextarea?.focus();
		document.addEventListener('keydown', handleKeyDown);
	});

	onDestroy(() => {
		document.removeEventListener('keydown', handleKeyDown);
	});

	$: canSave = back.trim() && (selectedDeckId || (showNewDeckInput && newDeckName.trim()));
</script>

<!-- svelte-ignore a11y_click_events_have_key_events a11y_no_noninteractive_element_interactions -->
<div
	class="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
	on:click={handleOverlayClick}
	role="dialog"
	aria-modal="true"
	aria-labelledby="flashcard-modal-title"
	transition:fade={{ duration: 150 }}
>
	<div
		class="mx-4 w-full max-w-lg rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 shadow-2xl"
		transition:scale={{ duration: 200, start: 0.95 }}
	>
		<!-- Header -->
		<div
			class="flex items-center justify-between border-b border-gray-200 dark:border-gray-700 px-6 py-4"
		>
			<h2
				id="flashcard-modal-title"
				class="flex items-center gap-2 text-lg font-semibold text-gray-900 dark:text-gray-100"
			>
				<svg class="w-5 h-5 text-[var(--accent-color)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
				</svg>
				Búa til minniskort
			</h2>
			<button
				on:click={onClose}
				class="rounded-lg p-2 text-gray-400 transition-colors hover:bg-gray-100 dark:hover:bg-gray-700 hover:text-gray-600 dark:hover:text-gray-200"
				aria-label="Loka"
			>
				<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
				</svg>
			</button>
		</div>

		<!-- Content -->
		<div class="p-6 space-y-4">
			<!-- Front (selected text) -->
			<div>
				<label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">
					Framhlið (spurning)
				</label>
				<blockquote
					class="rounded-lg border-l-4 border-[var(--accent-color)] bg-gray-50 dark:bg-gray-900 p-3 text-sm text-gray-700 dark:text-gray-300"
				>
					"{selectedText.length > 300 ? `${selectedText.slice(0, 300)}...` : selectedText}"
				</blockquote>
				{#if source}
					<p class="mt-1 text-xs text-gray-400 dark:text-gray-500">
						Heimild: {source}
					</p>
				{/if}
			</div>

			<!-- Back (answer) -->
			<div>
				<label
					for="flashcard-back"
					class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300"
				>
					Bakhlið (svar) <span class="text-red-500">*</span>
				</label>
				<textarea
					bind:this={backTextarea}
					bind:value={back}
					id="flashcard-back"
					placeholder="Skrifaðu svarið eða útskýringuna hér..."
					class="min-h-[100px] w-full resize-y rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-900 p-3 text-gray-900 dark:text-gray-100 placeholder-gray-400 dark:placeholder-gray-500 focus:border-[var(--accent-color)] focus:outline-none focus:ring-2 focus:ring-[var(--accent-color)]/20"
				></textarea>
				<p class="mt-1 text-xs text-gray-400 dark:text-gray-500">
					Ýttu á Ctrl+Enter til að vista
				</p>
			</div>

			<!-- Deck selection -->
			<div>
				<label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">
					Velja stokkur <span class="text-red-500">*</span>
				</label>

				{#if decks.length === 0 && !showNewDeckInput}
					<p class="text-sm text-gray-500 dark:text-gray-400 mb-2">
						Enginn stokkur til. Búðu til nýjan stokkur til að vista minniskortið.
					</p>
				{/if}

				{#if !showNewDeckInput && decks.length > 0}
					<select
						bind:value={selectedDeckId}
						class="w-full rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-900 px-3 py-2 text-gray-900 dark:text-gray-100 focus:border-[var(--accent-color)] focus:outline-none focus:ring-2 focus:ring-[var(--accent-color)]/20"
					>
						{#each decks as deck}
							<option value={deck.id}>{deck.name} ({deck.cards.length} kort)</option>
						{/each}
					</select>
				{/if}

				{#if showNewDeckInput}
					<input
						type="text"
						bind:value={newDeckName}
						placeholder="Nafn á nýjum stokkur..."
						class="w-full rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-900 px-3 py-2 text-gray-900 dark:text-gray-100 placeholder-gray-400 dark:placeholder-gray-500 focus:border-[var(--accent-color)] focus:outline-none focus:ring-2 focus:ring-[var(--accent-color)]/20"
					/>
				{/if}

				<button
					on:click={toggleNewDeck}
					class="mt-2 flex items-center gap-1 text-sm text-[var(--accent-color)] hover:underline"
				>
					{#if showNewDeckInput}
						<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 17l-5-5m0 0l5-5m-5 5h12" />
						</svg>
						Velja fyrirliggjandi stokkur
					{:else}
						<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
						</svg>
						Búa til nýjan stokkur
					{/if}
				</button>
			</div>
		</div>

		<!-- Footer -->
		<div
			class="flex justify-end gap-3 border-t border-gray-200 dark:border-gray-700 px-6 py-4"
		>
			<button
				on:click={onClose}
				class="rounded-lg border border-gray-300 dark:border-gray-600 px-4 py-2 text-sm font-medium text-gray-600 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-gray-700"
			>
				Hætta við
			</button>
			<button
				on:click={handleSave}
				disabled={!canSave}
				class="flex items-center gap-2 rounded-lg bg-[var(--accent-color)] px-4 py-2 text-sm font-medium text-white transition-colors hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed"
			>
				<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
				</svg>
				Vista minniskort
			</button>
		</div>
	</div>
</div>
